image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm run build
    - rm -r public
    - cp -r dist public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master
